#!/usr/bin/env ruby

if $PROGRAM_NAME == __FILE__
  ENV['BUNDLE_GEMFILE'] = File.expand_path('../../Gemfile', __FILE__)
  require 'rubygems'
  require 'bundler/setup'
end

require 'cocoapods-regression'

if ENV['CP_REGRESSION'].nil?
  $stderr.puts 'Please provide path to development CP in CP_REGRESSION env var.'
  exit(1)
end

if ARGV[0].nil?
  puts 'Available regression tests:'
  puts CocoaPods::Regression.apps.map { |app| "\t#{app}" }
  exit(0)
end

CocoaPods::Regression.test!(ARGV[0], ENV['CP_REGRESSION'])
